INSERT INTO ALIREZA.MENU (ID, ICON, NAME, PERSIAN_NAME, ROUTE, MENU_ID) VALUES (2, null, 'login', 'ورود', '/login', null);
INSERT INTO ALIREZA.MENU (ID, ICON, NAME, PERSIAN_NAME, ROUTE, MENU_ID) VALUES (1, null, 'home', 'خانه', '/', null);
INSERT INTO ALIREZA.MENU (ID, ICON, NAME, PERSIAN_NAME, ROUTE, MENU_ID) VALUES (3, null, 'logout', 'خروج', '/logout', null);
INSERT INTO ALIREZA.MENU (ID, ICON, NAME, PERSIAN_NAME, ROUTE, MENU_ID) VALUES (4, null, 'electronic', 'الکترونیک', '/electronic', null);
INSERT INTO ALIREZA.MENU (ID, ICON, NAME, PERSIAN_NAME, ROUTE, MENU_ID) VALUES (5, null, 'mobile', 'موبایل', '/electronic/mobile', 4);
INSERT INTO ALIREZA.MENU (ID, ICON, NAME, PERSIAN_NAME, ROUTE, MENU_ID) VALUES (6, null, 'computer', 'کامپوتر', '/electronic/pc', 4);
INSERT INTO ALIREZA.MENU (ID, ICON, NAME, PERSIAN_NAME, ROUTE, MENU_ID) VALUES (7, null, 'samsung', 'سامسونگ', '/electronic/mobile/samsung', 5);
INSERT INTO ALIREZA.MENU (ID, ICON, NAME, PERSIAN_NAME, ROUTE, MENU_ID) VALUES (8, null, 'vehicle', 'وسیله نقلیه', '/vehicle', null);
INSERT INTO ALIREZA.MENU (ID, ICON, NAME, PERSIAN_NAME, ROUTE, MENU_ID) VALUES (9, null, 'motor', 'موتور', '/vehicle/motor', 8);
INSERT INTO ALIREZA.MENU (ID, ICON, NAME, PERSIAN_NAME, ROUTE, MENU_ID) VALUES (10, null, 'car', 'ماشین', '/vehicle/car', 8);
INSERT INTO ALIREZA.MENU (ID, ICON, NAME, PERSIAN_NAME, ROUTE, MENU_ID) VALUES (11, null, 'BMW', 'ب ام و', '/vehicle/car/bmw', 10);
